<?php

// Load Permission 
module_load_include('inc', 'semanticbits', 'semanticbits.permissions');

/**
 * Implementing hook_menu()
 * Used to create Menu/Page
 */
function semanticbits_menu() {
  $menus = [];
  
  $menus['today-modified-pages'] = [
    'title' => t('Showing Today Modified Pages'),
    'description' => t('Showing Today Modified Pages'),
    'page callback' => '_get_today_modified_pages',
    'access arguments' => ['view today modified pages'],
  ];
  
  return $menus;
} 

/**
 * Implementing hook_block_info()
 * Used to define Block Informations
 */
function semanticbits_block_info() {
  $blocks = [];
  
  $blocks['today_modified_pages'] = [
    'info' => t('Showing Today Modified Pages'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  
  return $blocks;
} 

/**
 * Implementing hook_block_view()
 * Return a rendered or renderable view of a block.
 */
function semanticbits_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    case 'today_modified_pages':
      $block['subject'] = t('Showing Today Modified Pages');
      $output = _get_today_modified_pages();
      if(!empty($output))
      $output .= l(t('Full View'), 'today-modified-pages');
      $block['content'] = $output;
      break;
  }
  
  return $block;
} 

/**
 * Get Today Modified Pages
 * Render in list view
 * Rendering Each Pages teaser View
 */
function _get_today_modified_pages() {
  $todayStartTimestamp = strtotime("midnight", REQUEST_TIME);
  $todayEndTimestamp   = strtotime("tomorrow", $todayStartTimestamp) - 1;
  
  $query = db_select('node', 'page')->extend('PagerDefault');
  $query->condition('page.changed', [$todayStartTimestamp, $todayEndTimestamp], 'BETWEEN');
  $query->condition('page.status', 1);
  $query->fields('page', ['nid']);
  $query->limit(2);
  $query->orderBy('page.changed', 'DESC');
  $pages = $query->execute();
  
  $list_items = [];
  foreach($pages as $page) {
    $page = node_load($page->nid);
    $page_view = node_view($page, 'teaser');
    $list_items[] = drupal_render($page_view);
  }
  
  $list_view = theme('item_list', ['items' => $list_items]);
  $pager_view = theme('pager', ['quantity' => 5]);
  
  return $list_view . $pager_view;
} 

