<?php

// Load Permission 
module_load_include('inc', 'semanticbits', 'semanticbits.permissions');

/**
 * Implements hook_menu().
 * 	- Hook used to create pages/menus
 */
function semanticbits_menu() {
	$menus = [];
	
	$menus['pages/today-modified'] = [
		'title' => t('Today Modifed Pages'),
		'description' => t('View Today Modifed Pages'),
		'page callback' => '_get_today_modified_pages',
		'access arguments' => ['view today modified pages'],
	];
	
	return $menus;
}

/**
 * Implements hook_block_info().
 * 	- Hook used to define block informition
 */
function semanticbits_block_info() {
	$blocks = [];
	
	// To show today modified pages
  $blocks['today_modified_pages'] = array(
    'info' => t('Today Modifield Pages'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
	return $blocks;
}

/**
 * Implements hook_block_view().
 * 	- Hook used to define block informition
 */
function semanticbits_block_view($delta = '') {
	$block = array();
	
	switch ($delta) {
    case 'today_modified_pages':
      $block['subject'] = t('Today Modifield Pages');
			$output = _get_today_modified_pages();
			$output .= '<div style="text-align:right;">' . l('Full List', 'pages/today-modified', ['attributes' => ['style' => 'background-color:#d3d7d9;color:#000;padding:5px;']]) . '</div>';
			$block['content'] = $output;
			break;
	}
	
	return $block;
}

/**
 * Page Callback - pages/today-modified
 * Show today modified Pages
 */
function _get_today_modified_pages() {
	$beginOfDay = strtotime('today midnight');
	$endOfDay = strtotime("tomorrow", $beginOfDay) - 1;
	
	$query = db_select('node', 'node')->extend('PagerDefault');
	$query->condition('node.changed', [$beginOfDay, $endOfDay], 'BETWEEN');
	$query->fields('node', ['nid']);
	$query->orderBy('node.changed', 'DESC');
	$query->limit(3);
	$records = $query->execute();
	
	$header = ['Page', 'Operations'];
	
	$rows = [];
	foreach($records as $record) {
		$node = node_load($record->nid);
		$view = node_view($node, 'teaser');
		$rendered = drupal_render($view);
		
		$rows[] = [
			$rendered
		];
	}
	
	$pager = theme('pager', ['quantity' => 5]);
  $output = theme('item_list', ['items' => $rows]);
  
	return $output . $pager;	
}	
